  name: 'Create Dotenv File'
  description: 'Github Action to create a dotenv file'
  author: 'Bailey Tincher'
  branding:
    icon: 'briefcase'
    color: 'gray-dark'
  inputs:
    file_name:
      description: 'Filename to write dotenv file to'
      default: '.env'
      required: false
    directory:
      description: 'Directory to write the dotenv file in'
      default: '.'
      required: false
  runs:
    using: 'docker'
    image: 'Dockerfile'