name: Test action

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Make envfile
      uses: ./
      with:
        envkey_DEBUG: false
        envkey_SOME_API_KEY: "123456abcdef"
        envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
        some_other_variable: foobar
        file_name: .env

    - name: Verify envfile
      run: |
        cat .env
        TEST="SOME_API_KEY=123456abcdef\nSECRET_KEY=password123\nDEBUG=false"
        if [ "$TEST" != "$(cat .env)" ]
        then
            exit 1
        fi
